### ISSUE TITLE
Include PDFtk service

### ISSUE THREAD

**Issue by kristoftorfs** [torfs-ict/lando-symfony#6]
Add to `lando.yml.tpl`:

```yaml
services:
  pdftk:
    type: compose
    services:
      image: torfsict/docker-pdftk-webservice
      command: php /app/bin/console server:run 0.0.0.0:80
```

Add to `.env.dist`:
```
DATA_PDFTK_HOST=pdftk
```
